# Generated by Django 3.2.12 on 2022-04-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp1app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplingmodel',
            name='animal',
            field=models.TextField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='samplingmodel',
            name='control_number',
            field=models.TextField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='samplingmodel',
            name='control_situation',
            field=models.TextField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='samplingmodel',
            name='experiment_number',
            field=models.TextField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='samplingmodel',
            name='experiment_situation',
            field=models.TextField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='samplingmodel',
            name='method',
            field=models.TextField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='samplingmodel',
            name='purpose',
            field=models.TextField(default=None, max_length=100, null=True),
        ),
    ]
