# Generated by Django 3.2.12 on 2022-06-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp1app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplingmodel',
            name='image',
        ),
    ]
