# Generated by Django 3.2.12 on 2022-04-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp1app', '0004_auto_20220409_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplingmodel',
            name='purpose',
        ),
    ]
