# Generated by Django 3.2.12 on 2022-04-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp1app', '0005_remove_samplingmodel_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplingmodel',
            name='purpose',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
