# Generated by Django 3.2.12 on 2022-04-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp1app', '0006_samplingmodel_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalmodel',
            name='location',
        ),
    ]
