# Generated by Django 3.2.12 on 2022-04-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp1app', '0007_remove_animalmodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
