# Generated by Django 3.2.12 on 2022-04-10 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp1app', '0009_auto_20220410_0208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagedGroupModel',
        ),
    ]
